### ISSUE TITLE
Cannot find module es6.string.iterator

### ISSUE THREAD

**Issue by a-x-** [skidding/react-cosmos#192]
I tried to install cosmos into separate dir (`git clone`, `npm i`)

npm-debug.log: https://gist.github.com/a-x-/0ef7c4163bec33d376a5047f24897f54

```
Hash: 5ea3d2cd06a937387481
Version: webpack 1.13.2
Time: 61ms
    + 1 hidden modules

ERROR in Cannot find module '../../modules/es6.string.iterator'

> @ build:component-tree /Users/invntrm/Projects/Xp/react-cosmos
> PACKAGE=react-component-tree npm run build-babel


> @ build-babel /Users/invntrm/Projects/Xp/react-cosmos
> babel -D packages/$PACKAGE/src -d packages/$PACKAGE/lib

module.js:327
    throw err;
    ^

Error: Cannot find module '../../modules/es6.string.iterator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/invntrm/Projects/Xp/react-cosmos/node_modules/core-js/library/fn/symbol/iterator.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by skidding** [comment]
This seems similar: https://github.com/jspm/jspm-cli/issues/636 – Try installing the latest node/npm.
